import type { FormResponse, JourneyTemplateEntry } from '../schemas'
import { getStore } from '../storage'
import { computeTotalPauseShift, toScheduledDate } from './journeyDates'
import { applyResearchModules } from './journeyResearch'
import { buildPolicyScope } from './utils'

/**
 * A resolved, ordered step for a specific patient — after modifications and research overlays.
 * Recurring entries (recurrenceIntervalDays set) are expanded into multiple EffectiveSteps,
 * each with a unique id (`${baseId}__r${occurrenceIndex}`) and an occurrenceIndex.
 */
export type EffectiveStep = JourneyTemplateEntry & {
  isAdded: boolean
  isResearch: boolean
  /** True when this step was generated by recurring expansion. */
  isRecurring: boolean
  /** Which occurrence this is (0 = first, 1 = second, …). Only set when isRecurring=true. */
  occurrenceIndex?: number
  researchModuleId?: string
  replacesStepId?: string
  scheduledDate: string // YYYY-MM-DD relative to journey.startDate
}

/** Recurring step occurrences are expanded up to this many days from startDate. */
const RECURRENCE_HORIZON_DAYS = 5 * 365 // 5 years

/**
 * Resolves the effective, ordered steps for a patient journey.
 * Applies ADD_STEP / REMOVE_STEP modifications in chronological order.
 * SWITCH_TEMPLATE is already reflected in journey.journeyTemplateId and startDate.
 * Research module entries are then merged/inserted.
 */
export function getEffectiveSteps(journeyId: string): EffectiveStep[] {
  const state = getStore()
  const journey = state.patientJourneys.find((j) => j.id === journeyId)
  if (!journey) return []

  const template = state.journeyTemplates.find((t) => t.id === journey.journeyTemplateId)
  if (!template) return []

  const startMs = new Date(journey.startDate).getTime()

  // compute the combined pause shift including any current suspension
  const totalPauseShift = computeTotalPauseShift(journey)

  const toDate = (offsetDays: number) => toScheduledDate(startMs, offsetDays, totalPauseShift)

  let steps: EffectiveStep[] = []

  for (const e of template.entries) {
    if (e.recurrenceIntervalDays !== undefined) {
      // Expand into recurring occurrences up to the horizon.
      // Occurrence N+1 is scheduled at max(nominal, prevCompletion + intervalDays)
      // so that a late completion doesn't shorten the gap to the next follow-up.
      // The pause shift is baked in so that pausing/resuming pushes the whole series forward.
      const intervalMs = e.recurrenceIntervalDays * 86_400_000
      const horizonMs = startMs + (RECURRENCE_HORIZON_DAYS + totalPauseShift) * 86_400_000
      let occMs = startMs + (e.offsetDays + totalPauseShift) * 86_400_000
      let occIdx = 0
      while (occMs <= horizonMs) {
        const scheduledDate = new Date(occMs).toISOString().slice(0, 10)
        steps.push({
          ...e,
          id: `${e.id}__r${occIdx}`,
          isAdded: false,
          isResearch: false,
          isRecurring: true,
          occurrenceIndex: occIdx,
          scheduledDate,
        })
        // Next occurrence: advance by interval from this occurrence's scheduled date;
        // if this occurrence was already completed, advance from the actual completion date.
        const completion = (journey.recurringCompletions ?? []).find(
          (c) => c.stepId === e.id && c.occurrenceIndex === occIdx,
        )
        const anchorMs = completion
          ? Math.max(occMs, new Date(completion.completedAt).getTime())
          : occMs
        occMs = anchorMs + intervalMs
        occIdx++
      }
    } else {
      steps.push({
        ...e,
        isAdded: false,
        isResearch: false,
        isRecurring: false,
        scheduledDate: toDate(e.offsetDays),
      })
    }
  }

  const removedIds = new Set<string>()
  for (const mod of journey.modifications) {
    if (mod.type === 'REMOVE_STEP' && mod.stepId) {
      removedIds.add(mod.stepId)
    } else if (mod.type === 'ADD_STEP' && mod.entry) {
      steps.push({
        ...mod.entry,
        isAdded: true,
        isResearch: false,
        isRecurring: false,
        scheduledDate: toDate(mod.entry.offsetDays),
      })
    }
  }
  steps = steps.filter((s) => !removedIds.has(s.id))

  // apply any research‑module overlays / additions
  steps = applyResearchModules(steps, journey, startMs, totalPauseShift)

  return steps.sort((a, b) => a.offsetDays - b.offsetDays || a.order - b.order)
}

/**
 * Resolves base effective steps for a journey template + start date without
 * requiring a stored PatientJourney. Used for conflict detection before a
 * journey is created. Only template entries are resolved — no modifications,
 * research overlays or pause shifts apply.
 */
export function getEffectiveStepsForTemplate(
  templateId: string,
  startDate: string,
): EffectiveStep[] {
  const template = getStore().journeyTemplates.find((t) => t.id === templateId)
  if (!template) return []

  const startMs = new Date(startDate).getTime()
  const toDate = (offsetDays: number) =>
    new Date(startMs + offsetDays * 86_400_000).toISOString().slice(0, 10)

  const steps: EffectiveStep[] = []
  for (const e of template.entries) {
    if (e.recurrenceIntervalDays !== undefined) {
      // For conflict detection we only need the first occurrence.
      steps.push({
        ...e,
        id: `${e.id}__r0`,
        isAdded: false,
        isResearch: false,
        isRecurring: true,
        occurrenceIndex: 0,
        scheduledDate: toDate(e.offsetDays),
      })
    } else {
      steps.push({
        ...e,
        isAdded: false,
        isResearch: false,
        isRecurring: false,
        scheduledDate: toDate(e.offsetDays),
      })
    }
  }
  return steps.sort((a, b) => a.offsetDays - b.offsetDays || a.order - b.order)
}

/**
 * Builds the policy evaluation scope, also injecting semantic score aliases
 * from the patient's active journey steps (e.g. PNRS_week4, OSS_week8).
 */
export function buildPolicyScopeWithAliases(
  responses: FormResponse[],
  patientId: string,
): Record<string, number> {
  const state = getStore()
  const scope = buildPolicyScope(responses)

  const journey = state.patientJourneys
    .filter((j) => j.patientId === patientId && j.status === 'ACTIVE')
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0]

  if (!journey) return scope

  for (const step of getEffectiveSteps(journey.id)) {
    if (Object.keys(step.scoreAliases).length === 0) continue
    const stepResponses = responses
      .filter(
        (r) =>
          // Responses submitted through a journey step are linked by template entry id.
          r.journeyTemplateEntryId === step.id,
      )
      .sort((a, b) => new Date(b.submittedAt).getTime() - new Date(a.submittedAt).getTime())
    const latest = stepResponses[0]
    if (!latest) continue
    for (const [rawKey, alias] of Object.entries(step.scoreAliases)) {
      const value =
        latest.scores[rawKey] !== undefined ? latest.scores[rawKey] : Number(latest.answers[rawKey])
      if (!isNaN(value)) scope[alias] = value
    }
  }

  return scope
}

// ---------------------------------------------------------------------------
// Form deduplication
// ---------------------------------------------------------------------------

/**
 * An effective step that may span multiple patient journeys.
 * When a patient has parallel active/suspended journeys that both schedule the
 * same questionnaire template within overlapping windows on `date`, the steps
 * are merged into a single entry to avoid showing the form twice.
 */
export type MergedDueStep = EffectiveStep & {
  /** All journey IDs whose window for this template is open on `date`. */
  journeyIds: string[]
}

/**
 * Returns questionnaire steps that are due for a patient on a given date,
 * merged across all their active/suspended journeys so each questionnaire
 * template appears at most once regardless of how many parallel journeys
 * schedule it on the same day.
 */
export function getMergedDueStepsForPatient(patientId: string, date: string): MergedDueStep[] {
  const state = getStore()
  const journeys = state.patientJourneys.filter(
    (j) => j.patientId === patientId && (j.status === 'ACTIVE' || j.status === 'SUSPENDED'),
  )

  const byTemplate = new Map<string, MergedDueStep>()

  for (const journey of journeys) {
    for (const step of getEffectiveSteps(journey.id)) {
      if (!step.templateId) continue
      const windowStart = shiftDate(step.scheduledDate, -step.windowDays)
      const windowEnd = shiftDate(step.scheduledDate, step.windowDays)
      if (date < windowStart || date > windowEnd) continue

      // Skip steps that the patient already submitted a response for.
      // Stored journeyTemplateEntryId is always the base id (without __r<N>).
      const baseStepId = step.id.replace(/__r\d+$/, '')
      const alreadySubmitted = state.formResponses.some(
        (r) =>
          r.patientId === patientId &&
          r.patientJourneyId === journey.id &&
          r.journeyTemplateEntryId === baseStepId &&
          (step.occurrenceIndex === undefined || r.occurrenceIndex === step.occurrenceIndex),
      )
      if (alreadySubmitted) continue

      const existing = byTemplate.get(step.templateId)
      if (existing) {
        if (!existing.journeyIds.includes(journey.id)) existing.journeyIds.push(journey.id)
      } else {
        byTemplate.set(step.templateId, { ...step, journeyIds: [journey.id] })
      }
    }
  }

  return Array.from(byTemplate.values()).sort(
    (a, b) => a.scheduledDate.localeCompare(b.scheduledDate) || a.order - b.order,
  )
}

function shiftDate(ymd: string, days: number): string {
  return new Date(new Date(ymd).getTime() + days * 86_400_000).toISOString().slice(0, 10)
}
