import { getStore } from '../storage'
import { buildPolicyScope } from './utils'
import type { JourneyTemplateEntry, CaseCategory, FormResponse } from '../schemas'

/**
 * A resolved, ordered step for a specific patient — after modifications and research overlays.
 * resolvedInstruction is hydrated from instructionTemplateId (preferred) or instructionText.
 * Recurring entries (recurrenceIntervalDays set) are expanded into multiple EffectiveSteps,
 * each with a unique id (`${baseId}__r${occurrenceIndex}`) and an occurrenceIndex.
 */
export type EffectiveStep = JourneyTemplateEntry & {
  isAdded: boolean
  isResearch: boolean
  /** True when this step was generated by recurring expansion. */
  isRecurring: boolean
  /** Which occurrence this is (0 = first, 1 = second, …). Only set when isRecurring=true. */
  occurrenceIndex?: number
  researchModuleId?: string
  replacesStepId?: string
  scheduledDate: string // YYYY-MM-DD relative to journey.startDate
  resolvedInstruction?: string // hydrated instruction content (markdown)
}

/** Recurring step occurrences are expanded up to this many days from startDate. */
const RECURRENCE_HORIZON_DAYS = 5 * 365 // 5 years

/**
 * Resolves the effective, ordered steps for a patient journey.
 * Applies ADD_STEP / REMOVE_STEP modifications in chronological order.
 * SWITCH_TEMPLATE is already reflected in journey.journeyTemplateId and startDate.
 * Research module entries are then merged/inserted.
 * Instruction content is hydrated from instructionTemplateId or instructionText.
 */
export function getEffectiveSteps(journeyId: string): EffectiveStep[] {
  const state = getStore()
  const journey = state.patientJourneys.find((j) => j.id === journeyId)
  if (!journey) return []

  const template = state.journeyTemplates.find((t) => t.id === journey.journeyTemplateId)
  if (!template) return []

  const startMs = new Date(journey.startDate).getTime()
  const toDate = (offsetDays: number) =>
    new Date(startMs + offsetDays * 86_400_000).toISOString().slice(0, 10)

  const resolveInstruction = (entry: JourneyTemplateEntry): string | undefined => {
    if (entry.instructionTemplateId) {
      const it = (state.instructionTemplates ?? []).find(
        (t) => t.id === entry.instructionTemplateId,
      )
      return it?.content ?? entry.instructionText
    }
    return entry.instructionText
  }

  let steps: EffectiveStep[] = []

  for (const e of template.entries) {
    if (e.recurrenceIntervalDays !== undefined) {
      // Expand into recurring occurrences up to the horizon.
      // Occurrence N+1 is scheduled at max(nominal, prevCompletion + intervalDays)
      // so that a late completion doesn't shorten the gap to the next follow-up.
      const intervalMs = e.recurrenceIntervalDays * 86_400_000
      const horizonMs = startMs + RECURRENCE_HORIZON_DAYS * 86_400_000
      let occMs = startMs + e.offsetDays * 86_400_000
      let occIdx = 0
      while (occMs <= horizonMs) {
        const scheduledDate = new Date(occMs).toISOString().slice(0, 10)
        steps.push({
          ...e,
          id: `${e.id}__r${occIdx}`,
          isAdded: false,
          isResearch: false,
          isRecurring: true,
          occurrenceIndex: occIdx,
          scheduledDate,
          resolvedInstruction: resolveInstruction(e),
        })
        // Next occurrence: advance by interval from this occurrence's scheduled date;
        // if this occurrence was already completed, advance from the actual completion date.
        const completion = (journey.recurringCompletions ?? []).find(
          (c) => c.stepId === e.id && c.occurrenceIndex === occIdx,
        )
        const anchorMs = completion
          ? Math.max(occMs, new Date(completion.completedAt).getTime())
          : occMs
        occMs = anchorMs + intervalMs
        occIdx++
      }
    } else {
      steps.push({
        ...e,
        isAdded: false,
        isResearch: false,
        isRecurring: false,
        scheduledDate: toDate(e.offsetDays),
        resolvedInstruction: resolveInstruction(e),
      })
    }
  }

  const removedIds = new Set<string>()
  for (const mod of journey.modifications) {
    if (mod.type === 'REMOVE_STEP' && mod.stepId) {
      removedIds.add(mod.stepId)
    } else if (mod.type === 'ADD_STEP' && mod.entry) {
      steps.push({
        ...mod.entry,
        isAdded: true,
        isResearch: false,
        isRecurring: false,
        scheduledDate: toDate(mod.entry.offsetDays),
        resolvedInstruction: resolveInstruction(mod.entry),
      })
    }
  }
  steps = steps.filter((s) => !removedIds.has(s.id))

  for (const moduleId of journey.researchModuleIds) {
    const module = state.researchModules.find((m) => m.id === moduleId)
    if (!module) continue
    for (const entry of module.entries) {
      if (entry.replaceStepId) {
        const original = steps.find((s) => s.id === entry.replaceStepId)
        const researchStep: EffectiveStep = {
          id: entry.id,
          label: entry.label,
          offsetDays: original?.offsetDays ?? 0,
          windowDays: original?.windowDays ?? 2,
          order: original?.order ?? 999,
          templateId: entry.templateId,
          scoreAliases: original?.scoreAliases ?? {},
          scoreAliasLabels: original?.scoreAliasLabels ?? {},
          dashboardCategory: (original?.dashboardCategory ?? 'CONTROL') as CaseCategory,
          isAdded: false,
          isResearch: true,
          isRecurring: false,
          researchModuleId: moduleId,
          replacesStepId: entry.replaceStepId,
          scheduledDate: original?.scheduledDate ?? toDate(0),
          resolvedInstruction: original?.resolvedInstruction,
        }
        steps = steps.filter((s) => s.id !== entry.replaceStepId)
        steps.push(researchStep)
      } else if (entry.offsetDays !== undefined) {
        steps.push({
          id: entry.id,
          label: entry.label,
          offsetDays: entry.offsetDays,
          windowDays: 3,
          order: entry.offsetDays,
          templateId: entry.templateId,
          scoreAliases: {},
          scoreAliasLabels: {},
          dashboardCategory: 'CONTROL',
          isAdded: false,
          isResearch: true,
          isRecurring: false,
          researchModuleId: moduleId,
          scheduledDate: toDate(entry.offsetDays),
        })
      }
    }
  }

  return steps.sort((a, b) => a.offsetDays - b.offsetDays || a.order - b.order)
}

/**
 * Builds the policy evaluation scope, also injecting semantic score aliases
 * from the patient's active journey steps (e.g. PNRS_week4, OSS_week8).
 */
export function buildPolicyScopeWithAliases(
  responses: FormResponse[],
  patientId: string,
): Record<string, number> {
  const state = getStore()
  const scope = buildPolicyScope(responses)

  const journey = state.patientJourneys
    .filter((j) => j.patientId === patientId && j.status === 'ACTIVE')
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0]

  if (!journey) return scope

  for (const step of getEffectiveSteps(journey.id)) {
    if (Object.keys(step.scoreAliases).length === 0) continue
    const stepResponses = responses
      .filter((r) =>
        // Prefer exact step match via journeyStepId (set for responses submitted
        // after step keys were introduced). Fall back to templateId for legacy
        // responses that predate the journeyStepId field.
        r.journeyStepId ? r.journeyStepId === step.id : r.templateId === step.templateId,
      )
      .sort((a, b) => new Date(b.submittedAt).getTime() - new Date(a.submittedAt).getTime())
    const latest = stepResponses[0]
    if (!latest) continue
    for (const [rawKey, alias] of Object.entries(step.scoreAliases)) {
      const value =
        latest.scores[rawKey] !== undefined ? latest.scores[rawKey] : Number(latest.answers[rawKey])
      if (!isNaN(value)) scope[alias] = value
    }
  }

  return scope
}
