import type { JourneyTemplate } from '../../schemas'
import { daysAgo, iso } from '../shared'

export const jtKneePostop: JourneyTemplate = {
  id: 'jt-knee-postop',
  name: 'Knäartros — Postoperativ uppföljning',
  description:
    'Strukturerad rehabilitering efter knäprotesoperation med fysioinstruktioner och kontrolltillfällen.',
  referenceDateLabel: 'Operationsdatum',
  entries: [
    {
      id: 'jte-knee-po-1',
      label: 'Sårkontroll — vecka 1',
      offsetDays: 7,
      windowDays: 2,
      order: 1,
      templateId: 'qt-wound-pain',
      dashboardCategory: 'ACUTE',
      icon: 'Healing',
      scoreAliases: {},
      scoreAliasLabels: {},
      reviewTypes: ['XRAY'],
    },
    {
      id: 'jte-knee-po-2',
      label: 'Rörelseomfång — vecka 2',
      offsetDays: 14,
      windowDays: 3,
      order: 2,
      templateId: 'qt-function-oss',
      dashboardCategory: 'SUBACUTE',
      icon: 'Healing',
      scoreAliases: {},
      scoreAliasLabels: {},
    },
    {
      id: 'jte-knee-po-3',
      label: 'Funktionskontroll — vecka 6',
      offsetDays: 42,
      windowDays: 5,
      order: 3,
      templateId: 'qt-function-oss',
      dashboardCategory: 'CONTROL',
      icon: 'Healing',
      scoreAliases: { 'OSS.total': 'OSS_week6' },
      scoreAliasLabels: { OSS_week6: 'OSS-poäng vid vecka 6' },
    },
    {
      id: 'jte-knee-po-4',
      label: 'Uppföljning — 3 månader',
      offsetDays: 90,
      windowDays: 7,
      order: 4,
      templateId: 'qt-eq5d-oss',
      dashboardCategory: 'CONTROL',
      icon: 'Healing',
      scoreAliases: { 'OSS.total': 'OSS_3m', 'EQ5D.index': 'EQ5D_3m' },
      scoreAliasLabels: { OSS_3m: 'OSS vid 3 månader', EQ5D_3m: 'EQ-5D vid 3 månader' },
    },
  ],
  instructions: [
    {
      id: 'jti-knee-po-1',
      journeyTemplateId: 'jt-knee-postop',
      instructionTemplateId: 'it-knee-physio-week1',
      label: 'Träningsprogram vecka 1–2',
      startDayOffset: 0,
      endDayOffset: 27,
      order: 1,
      tags: ['physio', 'week1'],
      icon: 'FitnessCenter',
    },
    {
      id: 'jti-knee-po-2',
      journeyTemplateId: 'jt-knee-postop',
      instructionTemplateId: 'it-knee-physio-week4',
      label: 'Progressivt träningsprogram vecka 4–6',
      startDayOffset: 28,
      order: 2,
      tags: ['physio', 'week4'],
      icon: 'DirectionsRun',
    },
  ],
  createdAt: iso(daysAgo(180)),
}
