import { iso, daysAgo } from '../shared'
import type { JourneyTemplate } from '../../schemas'

export const jtProximalHumerus: JourneyTemplate = {
  id: 'jt-proximal-humerus',
  name: 'Proximala humerusfraktur',
  description:
    'Härledd från Standardfraktur — axelspecifika fysioterapiinstruktioner vid varje steg',
  parentTemplateId: 'jt-standard',
  derivedAt: iso(daysAgo(60)),
  entries: [
    {
      id: 'jte-ph-1',
      label: 'Dag 1–2',
      offsetDays: 1,
      windowDays: 1,
      order: 1,
      templateId: 'qt-numbness-infection',
      dashboardCategory: 'ACUTE',
      scoreAliases: { PNRS_1: 'PNRS_baseline' },
      scoreAliasLabels: { PNRS_baseline: 'VAS (PNRS) vid dag 1–2' },
      instructionTemplateId: 'it-wound-care',
    },
    {
      id: 'jte-ph-2',
      label: 'Dag 10–14 – stygnborttagning',
      offsetDays: 10,
      windowDays: 4,
      order: 2,
      templateId: 'qt-wound-pain',
      dashboardCategory: 'ACUTE',
      scoreAliases: { PNRS_2: 'PNRS_day14' },
      scoreAliasLabels: { PNRS_day14: 'VAS (PNRS) vid dag 10–14' },
      instructionTemplateId: 'it-proximal-humerus',
    },
    {
      id: 'jte-ph-3',
      label: 'Vecka 4 – fysiokontroll',
      offsetDays: 28,
      windowDays: 3,
      order: 3,
      templateId: 'qt-function-oss',
      dashboardCategory: 'SUBACUTE',
      scoreAliases: { PNRS_2: 'PNRS_week4', 'OSS.total': 'OSS_week4' },
      scoreAliasLabels: {
        PNRS_week4: 'VAS (PNRS) vid vecka 4',
        OSS_week4: 'OSS-poäng vid vecka 4',
      },
      instructionTemplateId: 'it-proximal-humerus',
    },
    {
      id: 'jte-ph-4',
      label: 'Vecka 6–8 – aktiv rörlighet',
      offsetDays: 49,
      windowDays: 7,
      order: 4,
      templateId: 'qt-function-oss',
      dashboardCategory: 'SUBACUTE',
      scoreAliases: { PNRS_2: 'PNRS_week8', 'OSS.total': 'OSS_week8' },
      scoreAliasLabels: {
        PNRS_week8: 'VAS (PNRS) vid vecka 6–8',
        OSS_week8: 'OSS-poäng vid vecka 6–8',
      },
      instructionTemplateId: 'it-proximal-humerus',
    },
    {
      id: 'jte-ph-5',
      label: '6 månader',
      offsetDays: 180,
      windowDays: 14,
      order: 5,
      templateId: 'qt-eq5d-oss',
      dashboardCategory: 'CONTROL',
      scoreAliases: { 'OSS.total': 'OSS_6m', 'EQ5D.index': 'EQ5D_6m', EQ_VAS: 'EQ_VAS_6m' },
      scoreAliasLabels: {
        OSS_6m: 'OSS-poäng vid 6 månader',
        EQ5D_6m: 'EQ-5D index vid 6 månader',
        EQ_VAS_6m: 'EQ VAS vid 6 månader',
      },
    },
    {
      id: 'jte-ph-6',
      label: '1 år',
      offsetDays: 365,
      windowDays: 14,
      order: 6,
      templateId: 'qt-eq5d-oss',
      dashboardCategory: 'CONTROL',
      scoreAliases: { 'OSS.total': 'OSS_1yr', 'EQ5D.index': 'EQ5D_1yr', EQ_VAS: 'EQ_VAS_1yr' },
      scoreAliasLabels: {
        OSS_1yr: 'OSS-poäng vid 1 år',
        EQ5D_1yr: 'EQ-5D index vid 1 år',
        EQ_VAS_1yr: 'EQ VAS vid 1 år',
      },
    },
  ],
  createdAt: iso(daysAgo(60)),
  referenceDateLabel: 'Operationsdatum',
}
