import { iso, daysAgo, daysFromNow } from './shared'
import type { Case } from '../schemas'

export const cases: Case[] = [
  // ── ACUTE ──────────────────────────────────────────────────────────────────
  {
    id: 'case-1',
    patientId: 'p-1',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'INFECTION_SUSPECTED'],
    policyWarnings: [
      {
        ruleId: 'rule-1',
        ruleName: 'Smärta minskar inte',
        severity: 'HIGH',
        triggeredValues: { PNRS_1: 8, PNRS_2: 8 },
        expression: 'PNRS_1 - PNRS_2 <= 0',
      },
    ],
    assignedRole: 'DOCTOR',
    assignedUserId: 'user-doc-1',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(2)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(2)),
    formSeriesId: 'fs-1',
  },
  {
    id: 'case-2',
    patientId: 'p-2',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'ABNORMAL_ANSWER'],
    policyWarnings: [
      {
        ruleId: 'rule-1',
        ruleName: 'Smärta minskar inte',
        severity: 'HIGH',
        triggeredValues: { PNRS_1: 7, PNRS_2: 8 },
        expression: 'PNRS_1 - PNRS_2 <= 0',
      },
      {
        ruleId: 'rule-3',
        ruleName: 'Låg livskvalitet (EQ-5D)',
        severity: 'MEDIUM',
        triggeredValues: { 'EQ5D.index': 0.4 },
        expression: 'EQ5D.index < 0.5',
      },
    ],
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(3)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(3)),
    formSeriesId: 'fs-1',
  },
  {
    id: 'case-7',
    patientId: 'p-7',
    category: 'ACUTE',
    status: 'NEW',
    triggers: ['NOT_OPENED'],
    policyWarnings: [],
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(1)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(1)),
    formSeriesId: 'fs-1',
  },
  // ── SUBACUTE ───────────────────────────────────────────────────────────────
  {
    id: 'case-3',
    patientId: 'p-3',
    category: 'SUBACUTE',
    status: 'TRIAGED',
    triggers: [],
    policyWarnings: [],
    assignedRole: 'NURSE',
    nextStep: 'DIGITAL_CONTROL',
    deadline: iso(daysFromNow(7)),
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(21)),
    lastActivityAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(21)),
    formSeriesId: 'fs-2',
  },
  {
    id: 'case-4',
    patientId: 'p-4',
    category: 'SUBACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['NOT_OPENED', 'SEEK_CONTACT'],
    policyWarnings: [],
    createdByUserId: 'user-nurse-2',
    scheduledAt: iso(daysAgo(25)),
    lastActivityAt: iso(daysAgo(5)),
    createdAt: iso(daysAgo(25)),
    formSeriesId: 'fs-2',
  },
  {
    id: 'case-8',
    patientId: 'p-8',
    category: 'SUBACUTE',
    status: 'FOLLOWING_UP',
    triggers: ['HIGH_PAIN'],
    policyWarnings: [
      {
        ruleId: 'rule-2',
        ruleName: 'Låg funktion (OSS)',
        severity: 'MEDIUM',
        triggeredValues: { 'OSS.total': 22 },
        expression: 'OSS.total < 30',
      },
    ],
    nextStep: 'NURSE_VISIT',
    deadline: iso(daysFromNow(3)),
    internalNote: 'Patienten rapporterar kvarstående svullnad. Sjuksköterskebesök inbokat.',
    assignedRole: 'NURSE',
    assignedUserId: 'user-nurse-1',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(18)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(18)),
    formSeriesId: 'fs-2',
  },
  // ── CONTROL ────────────────────────────────────────────────────────────────
  {
    id: 'case-5',
    patientId: 'p-5',
    category: 'CONTROL',
    status: 'NEEDS_REVIEW',
    triggers: ['LOW_FUNCTION', 'LOW_QOL'],
    policyWarnings: [
      {
        ruleId: 'rule-2',
        ruleName: 'Låg funktion (OSS)',
        severity: 'MEDIUM',
        triggeredValues: { 'OSS.total': 25 },
        expression: 'OSS.total < 30',
      },
      {
        ruleId: 'rule-3',
        ruleName: 'Låg livskvalitet (EQ-5D)',
        severity: 'MEDIUM',
        triggeredValues: { 'EQ5D.index': 0.45 },
        expression: 'EQ5D.index < 0.5',
      },
    ],
    createdByUserId: 'user-doc-1',
    scheduledAt: iso(daysAgo(63)),
    lastActivityAt: iso(daysAgo(3)),
    createdAt: iso(daysAgo(63)),
    formSeriesId: 'fs-3',
  },
  {
    id: 'case-6',
    patientId: 'p-6',
    category: 'CONTROL',
    status: 'CLOSED',
    triggers: [],
    policyWarnings: [],
    nextStep: 'DIGITAL_CONTROL',
    deadline: iso(daysFromNow(90)),
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    internalNote: 'Allt bra vid 6-månaderskontrollen. Nästa kontroll om 3 månader.',
    scheduledAt: iso(daysAgo(90)),
    lastActivityAt: iso(daysAgo(7)),
    createdAt: iso(daysAgo(90)),
    formSeriesId: 'fs-3',
  },
  {
    id: 'case-9',
    patientId: 'p-9',
    category: 'CONTROL',
    status: 'NEEDS_REVIEW',
    triggers: ['NO_RESPONSE'],
    policyWarnings: [],
    createdByUserId: 'user-doc-1',
    scheduledAt: iso(daysAgo(70)),
    lastActivityAt: iso(daysAgo(5)),
    createdAt: iso(daysAgo(70)),
    formSeriesId: 'fs-3',
  },
  {
    id: 'case-10',
    patientId: 'p-10',
    category: 'CONTROL',
    status: 'TRIAGED',
    triggers: [],
    policyWarnings: [],
    nextStep: 'PHYSIO_VISIT',
    deadline: iso(daysFromNow(14)),
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(100)),
    lastActivityAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(100)),
    formSeriesId: 'fs-3',
  },
]
