import { iso, daysAgo, daysFromNow } from './shared'
import type { Case } from '../schemas'

export const cases: Case[] = [
  // ── ACUTE ──────────────────────────────────────────────────────────────────
  {
    id: 'case-1',
    patientId: 'p-1',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'INFECTION_SUSPECTED'],
    policyWarnings: [
      {
        ruleId: 'rule-1',
        ruleName: 'Smärta minskar inte',
        severity: 'HIGH',
        triggeredValues: { PNRS_1: 8, PNRS_2: 8 },
        expression: 'PNRS_1 - PNRS_2 <= 0',
      },
    ],
    assignedRole: 'DOCTOR',
    assignedUserId: 'user-doc-1',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(2)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(2)),
    formSeriesId: 'fs-1',
    reviews: [],
  },
  {
    id: 'case-2',
    patientId: 'p-2',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'ABNORMAL_ANSWER'],
    policyWarnings: [
      {
        ruleId: 'rule-1',
        ruleName: 'Smärta minskar inte',
        severity: 'HIGH',
        triggeredValues: { PNRS_1: 7, PNRS_2: 8 },
        expression: 'PNRS_1 - PNRS_2 <= 0',
      },
      {
        ruleId: 'rule-3',
        ruleName: 'Låg livskvalitet (EQ-5D)',
        severity: 'MEDIUM',
        triggeredValues: { 'EQ5D.index': 0.4 },
        expression: 'EQ5D.index < 0.5',
      },
    ],
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(3)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(3)),
    formSeriesId: 'fs-1',
    reviews: [],
  },
  {
    id: 'case-7',
    patientId: 'p-7',
    category: 'ACUTE',
    status: 'NEW',
    triggers: ['NOT_OPENED'],
    policyWarnings: [],
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(1)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(1)),
    formSeriesId: 'fs-1',
    reviews: [],
  },
  // ── SUBACUTE ───────────────────────────────────────────────────────────────
  {
    id: 'case-3',
    patientId: 'p-3',
    category: 'SUBACUTE',
    status: 'TRIAGED',
    triggers: [],
    policyWarnings: [],
    assignedRole: 'NURSE',
    nextStep: 'DIGITAL_CONTROL',
    deadline: iso(daysFromNow(7)),
    internalNote:
      'Digital kontroll planerad. Säkerställ att patienten fått instruktioner för formuläret.',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(21)),
    lastActivityAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(21)),
    formSeriesId: 'fs-2',
    reviews: [],
  },
  {
    id: 'case-4',
    patientId: 'p-4',
    category: 'SUBACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['NOT_OPENED', 'SEEK_CONTACT'],
    policyWarnings: [],
    createdByUserId: 'user-nurse-2',
    scheduledAt: iso(daysAgo(25)),
    lastActivityAt: iso(daysAgo(5)),
    createdAt: iso(daysAgo(25)),
    formSeriesId: 'fs-2',
    reviews: [],
  },
  {
    id: 'case-8',
    patientId: 'p-8',
    category: 'SUBACUTE',
    status: 'FOLLOWING_UP',
    triggers: ['HIGH_PAIN'],
    policyWarnings: [
      {
        ruleId: 'rule-2',
        ruleName: 'Låg funktion (OSS)',
        severity: 'MEDIUM',
        triggeredValues: { 'OSS.total': 22 },
        expression: 'OSS.total < 30',
      },
    ],
    nextStep: 'NURSE_VISIT',
    deadline: iso(daysFromNow(3)),
    internalNote: 'Patienten rapporterar kvarstående svullnad. Sjuksköterskebesök inbokat.',
    assignedRole: 'NURSE',
    assignedUserId: 'user-nurse-1',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(18)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(18)),
    formSeriesId: 'fs-2',
    reviews: [],
  },
  // ── CONTROL ────────────────────────────────────────────────────────────────
  {
    id: 'case-5',
    patientId: 'p-5',
    category: 'CONTROL',
    status: 'NEEDS_REVIEW',
    triggers: ['LOW_FUNCTION', 'LOW_QOL'],
    policyWarnings: [
      {
        ruleId: 'rule-2',
        ruleName: 'Låg funktion (OSS)',
        severity: 'MEDIUM',
        triggeredValues: { 'OSS.total': 25 },
        expression: 'OSS.total < 30',
      },
      {
        ruleId: 'rule-3',
        ruleName: 'Låg livskvalitet (EQ-5D)',
        severity: 'MEDIUM',
        triggeredValues: { 'EQ5D.index': 0.45 },
        expression: 'EQ5D.index < 0.5',
      },
    ],
    createdByUserId: 'user-doc-1',
    scheduledAt: iso(daysAgo(63)),
    lastActivityAt: iso(daysAgo(3)),
    createdAt: iso(daysAgo(63)),
    formSeriesId: 'fs-3',
    reviews: [],
  },
  {
    id: 'case-6',
    patientId: 'p-6',
    category: 'CONTROL',
    status: 'CLOSED',
    triggers: [],
    policyWarnings: [],
    nextStep: 'DIGITAL_CONTROL',
    deadline: iso(daysFromNow(90)),
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    internalNote: 'Allt bra vid 6-månaderskontrollen. Nästa kontroll om 3 månader.',
    scheduledAt: iso(daysAgo(90)),
    lastActivityAt: iso(daysAgo(7)),
    createdAt: iso(daysAgo(90)),
    formSeriesId: 'fs-3',
    reviews: [],
  },
  {
    id: 'case-9',
    patientId: 'p-9',
    category: 'CONTROL',
    status: 'NEEDS_REVIEW',
    triggers: ['NO_RESPONSE'],
    policyWarnings: [],
    createdByUserId: 'user-doc-1',
    scheduledAt: iso(daysAgo(70)),
    lastActivityAt: iso(daysAgo(5)),
    createdAt: iso(daysAgo(70)),
    formSeriesId: 'fs-3',
    reviews: [],
  },
  {
    id: 'case-10',
    patientId: 'p-10',
    category: 'CONTROL',
    status: 'TRIAGED',
    triggers: [],
    policyWarnings: [],
    nextStep: 'PHYSIO_VISIT',
    deadline: iso(daysFromNow(14)),
    internalNote: 'Boka fysiobesök inom 2 veckor — rörlighetsproblem kvarstår sedan operationen.',
    assignedRole: 'NURSE',
    createdByUserId: 'user-pal-1',
    triagedByUserId: 'user-pal-1',
    scheduledAt: iso(daysAgo(100)),
    lastActivityAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(100)),
    formSeriesId: 'fs-3',
    reviews: [],
  },
  // ── Proximal humerus cases ─────────────────────────────────────────────
  {
    id: 'case-11',
    patientId: 'p-11',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'SEEK_CONTACT'],
    policyWarnings: [],
    assignedRole: 'NURSE',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(2)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(2)),
    formSeriesId: 'fs-1',
    reviews: [],
  },
  {
    id: 'case-12',
    patientId: 'p-12',
    category: 'SUBACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'LOW_FUNCTION'],
    policyWarnings: [
      {
        ruleId: 'rule-ph-2',
        ruleName: 'Hög smärta vid vecka 4',
        severity: 'HIGH',
        triggeredValues: { PNRS_week4: 7 },
        expression: 'PNRS_week4 >= 7',
      },
      {
        ruleId: 'rule-ph-3',
        ruleName: 'Låg axelfunktion vid vecka 4',
        severity: 'MEDIUM',
        triggeredValues: { OSS_week4: 20 },
        expression: 'OSS_week4 < 25',
      },
    ],
    assignedRole: 'DOCTOR',
    assignedUserId: 'user-doc-1',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(35)),
    lastActivityAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(35)),
    formSeriesId: 'fs-2',
    reviews: [],
  },
  // ── Distal radius cases ───────────────────────────────────────────────
  {
    id: 'case-13',
    patientId: 'p-13',
    category: 'ACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['HIGH_PAIN', 'ABNORMAL_ANSWER', 'XRAY_PENDING'],
    policyWarnings: [
      {
        ruleId: 'rule-dr-1',
        ruleName: 'Smärta minskar inte',
        severity: 'HIGH',
        triggeredValues: { PNRS_1: 6, PNRS_2: 8 },
        expression: 'PNRS_1 - PNRS_2 <= 0',
      },
    ],
    assignedRole: 'DOCTOR',
    assignedUserId: 'user-doc-1',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(14)),
    lastActivityAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(14)),
    formSeriesId: 'fs-1',
    reviews: [
      {
        id: 'rev-dr-1',
        type: 'XRAY',
        createdAt: iso(daysAgo(5)),
        createdByUserId: 'user-nurse-1',
        createdByRole: 'NURSE',
        reviewedAt: null,
        reviewedByUserId: undefined,
        reviewedByRole: undefined,
        note: null,
        source: 'JOURNEY',
      },
    ],
  },
  {
    id: 'case-14',
    patientId: 'p-14',
    category: 'SUBACUTE',
    status: 'NEEDS_REVIEW',
    triggers: ['LOW_FUNCTION', 'HIGH_PAIN', 'LAB_PENDING'],
    policyWarnings: [
      {
        ruleId: 'rule-dr-2',
        ruleName: 'Hög smärta vid gipsavtagning',
        severity: 'MEDIUM',
        triggeredValues: { PNRS_week4: 6 },
        expression: 'PNRS_week4 >= 6',
      },
      {
        ruleId: 'rule-dr-4',
        ruleName: 'Kvarstående låg handledsfunktion',
        severity: 'MEDIUM',
        triggeredValues: { OSS_week8: 20 },
        expression: 'OSS_week8 < 26',
      },
    ],
    assignedRole: 'NURSE',
    createdByUserId: 'user-nurse-1',
    scheduledAt: iso(daysAgo(52)),
    lastActivityAt: iso(daysAgo(3)),
    createdAt: iso(daysAgo(52)),
    formSeriesId: 'fs-2',
    reviews: [
      {
        id: 'rev-dr-2',
        type: 'LAB',
        createdAt: iso(daysAgo(7)),
        createdByUserId: 'user-nurse-1',
        createdByRole: 'NURSE',
        reviewedAt: null,
        reviewedByUserId: undefined,
        reviewedByRole: undefined,
        note: 'Väntar på blodprover för inflammation-markörer',
        source: 'MANUAL',
      },
    ],
  },
]
