import type { EpisodeOfCare } from '../schemas'
import { daysAgo, iso } from './shared'

export const episodesOfCare: EpisodeOfCare[] = [
  {
    id: 'ep-1',
    patientId: 'p-1',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(14)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-1',
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(14)),
  },
  {
    id: 'ep-2',
    patientId: 'p-2',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(10)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-2',
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(10)),
  },
  {
    id: 'ep-3',
    patientId: 'p-3',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(21)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-3',
    createdAt: iso(daysAgo(21)),
    updatedAt: iso(daysAgo(21)),
  },
  {
    id: 'ep-4',
    patientId: 'p-4',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(25)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-4',
    createdAt: iso(daysAgo(25)),
    updatedAt: iso(daysAgo(25)),
  },
  {
    id: 'ep-5',
    patientId: 'p-5',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(63)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-5',
    createdAt: iso(daysAgo(63)),
    updatedAt: iso(daysAgo(63)),
  },
  {
    id: 'ep-6',
    patientId: 'p-6',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'COMPLETED',
    openedAt: iso(daysAgo(90)),
    closedAt: iso(daysAgo(7)),
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-6',
    createdAt: iso(daysAgo(90)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'ep-7',
    patientId: 'p-7',
    label: 'Complex fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(1)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-7',
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'ep-8',
    patientId: 'p-8',
    label: 'Complex fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(18)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-8',
    createdAt: iso(daysAgo(18)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 'ep-9',
    patientId: 'p-9',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(70)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-9',
    createdAt: iso(daysAgo(70)),
    updatedAt: iso(daysAgo(70)),
  },
  {
    id: 'ep-10',
    patientId: 'p-10',
    label: 'Standard fracture follow-up — MOVE 2026',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(100)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-10',
    createdAt: iso(daysAgo(100)),
    updatedAt: iso(daysAgo(100)),
  },
  {
    id: 'ep-11',
    patientId: 'p-11',
    label: 'Proximal humerus fracture follow-up',
    clinicalArea: 'Schulter',
    status: 'OPEN',
    openedAt: iso(daysAgo(2)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-11',
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 'ep-12',
    patientId: 'p-12',
    label: 'Proximal humerus fracture follow-up',
    clinicalArea: 'Schulter',
    status: 'OPEN',
    openedAt: iso(daysAgo(35)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-12',
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'ep-13',
    patientId: 'p-13',
    label: 'Distal radius fracture follow-up',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(14)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-13',
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'ep-14',
    patientId: 'p-14',
    label: 'Distal radius fracture follow-up',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(52)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-14',
    createdAt: iso(daysAgo(52)),
    updatedAt: iso(daysAgo(3)),
  },
  // ── Knee OA episode (p-15) — 3 phases ────────────────────────────────────
  {
    id: 'ep-15',
    patientId: 'p-15',
    label: 'Knäartros höger knä',
    clinicalArea: 'Knä',
    status: 'OPEN',
    openedAt: iso(daysAgo(120)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-15',
    createdAt: iso(daysAgo(120)),
    updatedAt: iso(daysAgo(14)),
  },
  // ── Late-join demo episode (p-16) ────────────────────────────────────────
  {
    id: 'ep-16',
    patientId: 'p-16',
    label: 'Fraktur — inskrivning 4 veckor efter skada',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(0)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'case-16',
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
]
