import type { EpisodeOfCare } from '../schemas'
import { daysAgo, iso } from './shared'

export const episodesOfCare: EpisodeOfCare[] = [
  {
    id: 'ep-1',
    patientId: 'p-1',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(14)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-1',
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(14)),
  },
  {
    id: 'ep-2',
    patientId: 'p-2',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(10)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-2',
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(10)),
  },
  {
    id: 'ep-3',
    patientId: 'p-3',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(21)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-3',
    createdAt: iso(daysAgo(21)),
    updatedAt: iso(daysAgo(21)),
  },
  {
    id: 'ep-4',
    patientId: 'p-4',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(25)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-4',
    createdAt: iso(daysAgo(25)),
    updatedAt: iso(daysAgo(25)),
  },
  {
    id: 'ep-5',
    patientId: 'p-5',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(63)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-5',
    createdAt: iso(daysAgo(63)),
    updatedAt: iso(daysAgo(63)),
  },
  {
    id: 'ep-6',
    patientId: 'p-6',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'COMPLETED',
    openedAt: iso(daysAgo(90)),
    closedAt: iso(daysAgo(7)),
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-6',
    createdAt: iso(daysAgo(90)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'ep-7',
    patientId: 'p-7',
    label: 'Complex fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(1)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-7',
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'ep-8',
    patientId: 'p-8',
    label: 'Complex fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(18)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-8',
    createdAt: iso(daysAgo(18)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 'ep-9',
    patientId: 'p-9',
    label: 'Standard fracture follow-up',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(70)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-9',
    createdAt: iso(daysAgo(70)),
    updatedAt: iso(daysAgo(70)),
  },
  {
    id: 'ep-10',
    patientId: 'p-10',
    label: 'Standard fracture follow-up — MOVE 2026',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(100)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-10',
    createdAt: iso(daysAgo(100)),
    updatedAt: iso(daysAgo(100)),
  },
  {
    id: 'ep-11',
    patientId: 'p-11',
    label: 'Proximal humerus fracture follow-up',
    clinicalArea: 'Schulter',
    status: 'OPEN',
    openedAt: iso(daysAgo(2)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-11',
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 'ep-12',
    patientId: 'p-12',
    label: 'Proximal humerus fracture follow-up',
    clinicalArea: 'Schulter',
    status: 'OPEN',
    openedAt: iso(daysAgo(35)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-12',
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'ep-13',
    patientId: 'p-13',
    label: 'Distal radius fracture follow-up',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(14)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'c-13',
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'ep-14',
    patientId: 'p-14',
    label: 'Distal radius fracture follow-up',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(52)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'c-14',
    createdAt: iso(daysAgo(52)),
    updatedAt: iso(daysAgo(3)),
  },
  // ── Knee OA episode (p-15) — 3 phases ────────────────────────────────────
  {
    id: 'ep-15',
    patientId: 'p-15',
    label: 'Knäartros höger knä',
    clinicalArea: 'Knä',
    status: 'OPEN',
    openedAt: iso(daysAgo(120)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-15',
    createdAt: iso(daysAgo(120)),
    updatedAt: iso(daysAgo(14)),
  },
  // ── Late-join demo episode (p-16) ────────────────────────────────────────
  {
    id: 'ep-16',
    patientId: 'p-16',
    label: 'Fraktur — inskrivning 4 veckor efter skada',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(0)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'case-16',
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
  // ── Hindfoot elective surgery pathway — Eva Lindqvist (p-19) ─────────────
  {
    // Full 3-phase hindfoot journey — now at 6-month post-op followup
    id: 'ep-19',
    patientId: 'p-19',
    label: 'Hindfoot fusion — subtalar artros höger fot',
    clinicalArea: 'Fot & Fotled',
    status: 'OPEN',
    openedAt: iso(daysAgo(540)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-19',
    createdAt: iso(daysAgo(540)),
    updatedAt: iso(daysAgo(0)),
  },
  // ── Hindfoot WL mid-journey — Margareta Pettersson (p-20) ────────────────
  {
    // Mid-waiting-list: 3-month surgery interest form pending (NOT_OPENED)
    id: 'ep-20',
    patientId: 'p-20',
    label: 'Hindfoot fusion — planus deformitet vänster fot',
    clinicalArea: 'Fot & Fotled',
    status: 'OPEN',
    openedAt: iso(daysAgo(300)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'case-20',
    createdAt: iso(daysAgo(300)),
    updatedAt: iso(daysAgo(5)),
  },
  // ── Journey-switch demo — Axel Lindström (p-21) ───────────────────────────
  {
    // Ankle fracture: simple standard → switched to complex at day 3
    id: 'ep-21',
    patientId: 'p-21',
    label: 'Ankelfraktur — omklassificerad bimalleolär',
    clinicalArea: 'Fot & Fotled',
    status: 'OPEN',
    openedAt: iso(daysAgo(42)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-21',
    createdAt: iso(daysAgo(42)),
    updatedAt: iso(daysAgo(2)),
  },
  // ── Two simultaneous fractures — Gunnar Eriksson (p-22) ──────────────────
  {
    // Right distal radius — reasonable recovery
    id: 'ep-22',
    patientId: 'p-22',
    label: 'Distala radiusfraktur höger — trauma 35 dagar sedan',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(35)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'case-22',
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    // Left calcaneus — same patient, separate episode, difficult recovery
    id: 'ep-23',
    patientId: 'p-22',
    label: 'Calcaneusfraktur vänster — trauma 35 dagar sedan',
    clinicalArea: 'Fot & Fotled',
    status: 'OPEN',
    openedAt: iso(daysAgo(35)),
    closedAt: null,
    responsibleUserId: 'user-doc-1',
    primaryCaseId: 'case-23',
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(1)),
  },
  // ── Old fracture 1yr + new acute fracture — Birgit Magnusson (p-23) ───────
  {
    // Femoral neck fracture 1 year ago — now at 1-year control
    id: 'ep-24',
    patientId: 'p-23',
    label: 'Proximal femurfraktur höger — 1-årsuppföljning',
    clinicalArea: 'Ortopedi',
    status: 'OPEN',
    openedAt: iso(daysAgo(365)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-24',
    createdAt: iso(daysAgo(365)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    // New distal radius fracture 10 days ago — concurrent with 1-year control
    id: 'ep-25',
    patientId: 'p-23',
    label: 'Distala radiusfraktur vänster — nytt trauma',
    clinicalArea: 'Hand',
    status: 'OPEN',
    openedAt: iso(daysAgo(10)),
    closedAt: null,
    responsibleUserId: 'user-pal-1',
    primaryCaseId: 'case-25',
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(1)),
  },
]
