import type { FormResponse } from '../schemas'
import { daysAgo, iso } from './shared'

export const formResponses: FormResponse[] = [
  // Anders — case-1 — acute, high pain + infection
  {
    id: 'fr-1',
    patientId: 'p-1',
    templateId: 'qt-numbness-infection',
    caseId: 'case-1',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: true, INF_FEVER: true, PNRS_1: 8 },
    scores: {},
    submittedAt: iso(daysAgo(13)),
  },
  {
    id: 'fr-2',
    patientId: 'p-1',
    templateId: 'qt-wound-pain',
    caseId: 'case-1',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: true, PNRS_2: 8, PNRS_NIGHT: 7 },
    scores: {},
    submittedAt: iso(daysAgo(4)),
  },
  // Elin — case-2 — pain increasing + low QoL
  {
    id: 'fr-3',
    patientId: 'p-2',
    templateId: 'qt-numbness-infection',
    caseId: 'case-2',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 7 },
    scores: {},
    submittedAt: iso(daysAgo(9)),
  },
  {
    id: 'fr-4',
    patientId: 'p-2',
    templateId: 'qt-wound-pain',
    caseId: 'case-2',
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 8, PNRS_NIGHT: 6 },
    scores: {},
    submittedAt: iso(daysAgo(2)),
  },
  // Karl — case-3 — subacute, good progress
  {
    id: 'fr-5',
    patientId: 'p-3',
    templateId: 'qt-function-oss',
    caseId: 'case-3',
    answers: { OSS_1: 4, OSS_2: 3, OSS_3: 4, OSS_4: 4, OSS_5: 3, PNRS_2: 3 },
    scores: { 'OSS.total': 36 },
    submittedAt: iso(daysAgo(2)),
  },
  // Britta — case-8 — subacute following up, low function
  {
    id: 'fr-8',
    patientId: 'p-8',
    templateId: 'qt-function-oss',
    caseId: 'case-8',
    answers: { OSS_1: 2, OSS_2: 2, OSS_3: 3, OSS_4: 2, OSS_5: 2, PNRS_2: 6 },
    scores: { 'OSS.total': 22 },
    submittedAt: iso(daysAgo(4)),
  },
  // Torkel — case-5 — control, low function + low QoL
  {
    id: 'fr-5b',
    patientId: 'p-5',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-5',
    answers: {
      EQ_MOB: '2',
      EQ_SELF: '1',
      EQ_ACT: '2',
      EQ_PAIN: '3',
      EQ_ANX: '2',
      EQ_VAS: 45,
      OSS_1: 2,
      OSS_2: 3,
      OSS_3: 2,
      OSS_4: 2,
      OSS_5: 3,
      FREE_TEXT: 'Jag har fortfarande ont men det är bättre än förut. Svårt att sova.',
    },
    scores: { 'OSS.total': 25, 'EQ5D.index': 0.45 },
    submittedAt: iso(daysAgo(3)),
  },
  // Maria — case-6 — closed, good result
  {
    id: 'fr-6',
    patientId: 'p-6',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-6',
    answers: {
      EQ_MOB: '1',
      EQ_SELF: '1',
      EQ_ACT: '1',
      EQ_PAIN: '1',
      EQ_ANX: '1',
      EQ_VAS: 85,
      OSS_1: 4,
      OSS_2: 4,
      OSS_3: 5,
      OSS_4: 4,
      OSS_5: 4,
      FREE_TEXT: 'Mår mycket bra. Är nöjd med behandlingen.',
    },
    scores: { 'OSS.total': 38, 'EQ5D.index': 0.9 },
    submittedAt: iso(daysAgo(7)),
  },
  // Lena — case-10 — control, triaged to physio
  {
    id: 'fr-10',
    patientId: 'p-10',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-10',
    answers: {
      EQ_MOB: '2',
      EQ_SELF: '1',
      EQ_ACT: '2',
      EQ_PAIN: '2',
      EQ_ANX: '1',
      EQ_VAS: 65,
      OSS_1: 3,
      OSS_2: 3,
      OSS_3: 4,
      OSS_4: 3,
      OSS_5: 3,
      FREE_TEXT: 'Lite stel i axeln på morgnarna men förbättras under dagen.',
    },
    scores: { 'OSS.total': 32, 'EQ5D.index': 0.72 },
    submittedAt: iso(daysAgo(2)),
  },
  // ── Proximal humerus patients ─────────────────────────────────────────────
  // Ingrid — case-11 — acute, high pain + numbness (baseline only)
  {
    id: 'fr-p11-1',
    patientId: 'p-11',
    templateId: 'qt-numbness-infection',
    caseId: 'case-11',
    answers: { NUMB_1: true, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 9 },
    scores: {},
    submittedAt: iso(daysAgo(2)),
  },
  // Johan — case-12 — subacute, week 4: high pain + low shoulder function
  {
    id: 'fr-p12-1',
    patientId: 'p-12',
    templateId: 'qt-numbness-infection',
    caseId: 'case-12',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 6 },
    scores: {},
    submittedAt: iso(daysAgo(34)),
  },
  {
    id: 'fr-p12-2',
    patientId: 'p-12',
    templateId: 'qt-wound-pain',
    caseId: 'case-12',
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 5, PNRS_NIGHT: 4 },
    scores: {},
    submittedAt: iso(daysAgo(25)),
  },
  {
    id: 'fr-p12-3',
    patientId: 'p-12',
    templateId: 'qt-function-oss',
    caseId: 'case-12',
    // PNRS_week4=7 (≥ 7 → rule-ph-2), OSS_week4=20 (< 25 → rule-ph-3)
    answers: { OSS_1: 2, OSS_2: 2, OSS_3: 2, OSS_4: 2, OSS_5: 2, PNRS_2: 7 },
    scores: { 'OSS.total': 20 },
    submittedAt: iso(daysAgo(7)),
  },
  // ── Distal radius patients ───────────────────────────────────────────────
  // Ragnhild — case-13 — acute, pain increasing (PNRS_1=6 → PNRS_2=8 → rule-dr-1)
  {
    id: 'fr-p13-1',
    patientId: 'p-13',
    templateId: 'qt-numbness-infection',
    caseId: 'case-13',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 6 },
    scores: {},
    submittedAt: iso(daysAgo(13)),
  },
  {
    id: 'fr-p13-2',
    patientId: 'p-13',
    templateId: 'qt-wound-pain',
    caseId: 'case-13',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: true, PNRS_2: 8, PNRS_NIGHT: 7 },
    scores: {},
    submittedAt: iso(daysAgo(1)),
  },
  // Bert — case-14 — subacute week 8: pain resurges + function worsens
  {
    id: 'fr-p14-1',
    patientId: 'p-14',
    templateId: 'qt-numbness-infection',
    caseId: 'case-14',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 5 },
    scores: {},
    submittedAt: iso(daysAgo(51)),
  },
  {
    id: 'fr-p14-2',
    patientId: 'p-14',
    templateId: 'qt-wound-pain',
    caseId: 'case-14',
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 4, PNRS_NIGHT: 3 },
    scores: {},
    submittedAt: iso(daysAgo(38)),
  },
  {
    id: 'fr-p14-3',
    patientId: 'p-14',
    templateId: 'qt-function-oss',
    caseId: 'case-14',
    // week 4 response — decent but not alarming
    answers: { OSS_1: 3, OSS_2: 4, OSS_3: 4, OSS_4: 3, OSS_5: 4, PNRS_2: 4 },
    scores: { 'OSS.total': 36 },
    submittedAt: iso(daysAgo(24)),
  },
  {
    id: 'fr-p14-4',
    patientId: 'p-14',
    templateId: 'qt-function-oss',
    caseId: 'case-14',
    // week 8 response — pain resurges and function deteriorates
    // PNRS_week4=6 (≥ 6 → rule-dr-2), OSS_week8=20 (< 26 → rule-dr-4)
    answers: { OSS_1: 2, OSS_2: 2, OSS_3: 2, OSS_4: 2, OSS_5: 2, PNRS_2: 6 },
    scores: { 'OSS.total': 20 },
    submittedAt: iso(daysAgo(3)),
  },

  // ── Karin Karlberg — Knee OA 3-phase journey (p-15) ──────────────────────
  // Phase 1: Remissfas (pj-knee-1, started daysAgo(120))
  {
    id: 'fr-knee-ref-1',
    patientId: 'p-15',
    templateId: 'qt-numbness-infection',
    caseId: 'case-15',
    patientJourneyId: 'pj-knee-1',
    journeyTemplateEntryId: 'jte-knee-ref-1',
    // Day 1 baseline: no red flags, moderate OA pain
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 6 },
    scores: {},
    submittedAt: iso(daysAgo(119)),
  },
  {
    id: 'fr-knee-ref-2',
    patientId: 'p-15',
    templateId: 'qt-wound-pain',
    caseId: 'case-15',
    patientJourneyId: 'pj-knee-1',
    journeyTemplateEntryId: 'jte-knee-ref-2',
    // Day 7 symptom check before orthopaedic visit: significant knee pain, no wound issues
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 7, PNRS_NIGHT: 5 },
    scores: {},
    submittedAt: iso(daysAgo(113)),
  },

  // Phase 2: Väntelista operation (pj-knee-2, started daysAgo(90))
  // Health declaration at queue entry. Quarterly controls were never reached — surgery
  // happened at day 76 (daysAgo(14)), before the first 90-day recurrence fell due.
  {
    id: 'fr-knee-sq-1',
    patientId: 'p-15',
    templateId: 'qt-numbness-infection',
    caseId: 'case-15',
    patientJourneyId: 'pj-knee-2',
    journeyTemplateEntryId: 'jte-knee-sq-1',
    // Health declaration on joining the waiting list: pain worsening after conservative treatment
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 7 },
    scores: {},
    submittedAt: iso(daysAgo(89)),
  },

  // Phase 3: Postoperativ uppföljning (pj-knee-3, started daysAgo(14) — surgery date)
  // Week 1 wound control: healing on track, still early post-op pain
  {
    id: 'fr-knee-po-1',
    patientId: 'p-15',
    templateId: 'qt-wound-pain',
    caseId: 'case-15',
    patientJourneyId: 'pj-knee-3',
    journeyTemplateEntryId: 'jte-knee-po-1',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: false, PNRS_2: 5, PNRS_NIGHT: 6 },
    scores: {},
    submittedAt: iso(daysAgo(7)),
  },

  // ── Eva Lindqvist — Hindfoot surgery 3-phase journey (p-19) ──────────────
  // Phase 1: Preop intake (pj-hf-19a, ~540 days ago)
  {
    id: 'fr-hf-19-intake',
    patientId: 'p-19',
    templateId: 'qt-preop-intake',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19a',
    journeyTemplateEntryId: 'jte-hf-ref-1',
    answers: {
      HEIGHT: 162,
      WEIGHT: 74,
      PREV_SURGERY: true,
      PREV_SURGERY_DETAILS: 'Appendixoperation 1998',
      WALKING_AID: 'CRUTCHES',
      HOME_CARE: false,
      LIVES_ALONE: false,
      STAIRS_AT_HOME: true,
      MEDICATIONS: 'Metformin 500 mg x2, Atorvastatin 20 mg x1',
      ALLERGIES: 'Penicillin (utslag)',
      SMOKING: 'NEVER',
      PNRS_1: 6,
    },
    scores: {},
    submittedAt: iso(daysAgo(539)),
  },
  // Phase 2: Waiting-list status check (pj-hf-19b, ~day 60 of WL = daysAgo(510-60)=daysAgo(450))
  {
    id: 'fr-hf-19-wl-status',
    patientId: 'p-19',
    templateId: 'qt-waitinglist-status',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19b',
    journeyTemplateEntryId: 'jte-hf-wl-1',
    answers: {
      WL_NEW_DISEASE: false,
      WL_NEW_MEDICATION: false,
      WL_HOSPITALIZED: false,
      WL_COMMENTS: '',
      PNRS_1: 5,
    },
    scores: {},
    submittedAt: iso(daysAgo(450)),
  },
  // Phase 2: Surgery interest check (pj-hf-19b, ~day 90 of WL = daysAgo(420))
  {
    id: 'fr-hf-19-interest',
    patientId: 'p-19',
    templateId: 'qt-surgery-interest',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19b',
    journeyTemplateEntryId: 'jte-hf-wl-2',
    answers: {
      STILL_INTERESTED: true,
      CONCERNS: 'Undrar hur lång rehabiliteringstiden är och när jag kan börja gå normalt.',
      PNRS_1: 6,
    },
    scores: {},
    submittedAt: iso(daysAgo(420)),
  },
  // Phase 2: Health declaration before surgery (pj-hf-19b, ~day 120 of WL = daysAgo(390))
  {
    id: 'fr-hf-19-health-decl',
    patientId: 'p-19',
    templateId: 'qt-health-declaration',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19b',
    journeyTemplateEntryId: 'jte-hf-wl-3',
    answers: {
      HEIGHT: 162,
      WEIGHT: 75,
      PREV_SURGERY: true,
      HEREDITARY: false,
      HAS_HEART_DISEASE: false,
      HAS_HYPERTENSION: false,
      HAS_ANTICOAG: false,
      HAS_STROKE: false,
      HAS_DIABETES: true,
      HAS_LUNG_DISEASE: false,
      HAS_KIDNEY_DISEASE: false,
      CARE_ABROAD: false,
      MRSA: false,
      MEDICATIONS: 'Metformin 500 mg x2, Atorvastatin 20 mg x1',
      ALLERGIES: 'Penicillin (utslag)',
      SMOKING: 'NEVER',
      ALCOHOL: 'NONE',
    },
    scores: {},
    submittedAt: iso(daysAgo(390)),
  },
  // Phase 3: Week 1 wound check (pj-hf-19c, daysAgo(173))
  {
    id: 'fr-hf-19-po-w1',
    patientId: 'p-19',
    templateId: 'qt-wound-pain',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19c',
    journeyTemplateEntryId: 'jte-hf-po-1',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: false, PNRS_2: 6, PNRS_NIGHT: 7 },
    scores: {},
    submittedAt: iso(daysAgo(173)),
  },
  // Phase 3: Week 2 X-ray + suture removal (pj-hf-19c, daysAgo(166))
  {
    id: 'fr-hf-19-po-w2',
    patientId: 'p-19',
    templateId: 'qt-wound-pain',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19c',
    journeyTemplateEntryId: 'jte-hf-po-2',
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 5, PNRS_NIGHT: 5 },
    scores: {},
    submittedAt: iso(daysAgo(166)),
  },
  // Phase 3: Week 6 cast removal + function (pj-hf-19c, daysAgo(138))
  {
    id: 'fr-hf-19-po-w6',
    patientId: 'p-19',
    templateId: 'qt-function-oss',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19c',
    journeyTemplateEntryId: 'jte-hf-po-3',
    answers: { OSS_1: 3, OSS_2: 3, OSS_3: 3, OSS_4: 3, OSS_5: 3, PNRS_2: 4 },
    scores: { 'OSS.total': 30 },
    submittedAt: iso(daysAgo(138)),
  },
  // Phase 3: 6-month followup (pj-hf-19c, just submitted today — triggers current case)
  {
    id: 'fr-hf-19-6m',
    patientId: 'p-19',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-19',
    patientJourneyId: 'pj-hf-19c',
    journeyTemplateEntryId: 'jte-hf-po-4',
    answers: {
      EQ_MOB: '2',
      EQ_SELF: '1',
      EQ_ACT: '2',
      EQ_PAIN: '2',
      EQ_ANX: '1',
      EQ_VAS: 68,
      OSS_1: 3,
      OSS_2: 4,
      OSS_3: 4,
      OSS_4: 3,
      OSS_5: 4,
      FREE_TEXT:
        'Bättre än innan operationen. Kan gå kortare sträckor utan kryckor men fortfarande jobbigt i sluttande terräng.',
    },
    scores: { 'OSS.total': 34, 'EQ5D.index': 0.72, EQ_VAS: 68 },
    submittedAt: iso(daysAgo(0)),
  },

  // ── Margareta Pettersson — Mid-WL hindfoot journey (p-20) ────────────────
  // Phase 1: Preop intake (completed ~300 days ago)
  {
    id: 'fr-hf-20-intake',
    patientId: 'p-20',
    templateId: 'qt-preop-intake',
    caseId: 'case-20',
    patientJourneyId: 'pj-hf-20a',
    journeyTemplateEntryId: 'jte-hf-ref-1',
    answers: {
      HEIGHT: 158,
      WEIGHT: 82,
      PREV_SURGERY: false,
      WALKING_AID: 'NONE',
      HOME_CARE: false,
      LIVES_ALONE: true,
      STAIRS_AT_HOME: false,
      MEDICATIONS: 'Ibuprofen vid behov',
      ALLERGIES: '',
      SMOKING: 'QUIT_OVER_6M',
      PNRS_1: 5,
    },
    scores: {},
    submittedAt: iso(daysAgo(299)),
  },
  // Phase 2: 2-month WL status check (day 60 of WL = daysAgo(205-60)=daysAgo(145))
  {
    id: 'fr-hf-20-wl-status',
    patientId: 'p-20',
    templateId: 'qt-waitinglist-status',
    caseId: 'case-20',
    patientJourneyId: 'pj-hf-20b',
    journeyTemplateEntryId: 'jte-hf-wl-1',
    answers: {
      WL_NEW_DISEASE: false,
      WL_NEW_MEDICATION: true,
      WL_HOSPITALIZED: false,
      WL_COMMENTS: 'Fick Lisinopril 5 mg mot blodtryck.',
      PNRS_1: 5,
    },
    scores: {},
    submittedAt: iso(daysAgo(145)),
  },
  // Phase 2: 3-month surgery interest form sent but NOT opened (daysAgo(115), case status NEW)
  // — no form response added intentionally (patient never opened it)

  // ── Axel Lindström — Journey-switch ankle fracture (p-21) ────────────────
  // Phase 1: Standard — day 1 numbness/infection check
  {
    id: 'fr-ax-21-d1',
    patientId: 'p-21',
    templateId: 'qt-numbness-infection',
    caseId: 'case-21',
    patientJourneyId: 'pj-ax-21a',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 7 },
    scores: {},
    submittedAt: iso(daysAgo(41)),
  },
  // Phase 1: Standard — day 3 wound check (before reclassification)
  {
    id: 'fr-ax-21-d3',
    patientId: 'p-21',
    templateId: 'qt-wound-pain',
    caseId: 'case-21',
    patientJourneyId: 'pj-ax-21a',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: false, PNRS_2: 7, PNRS_NIGHT: 6 },
    scores: {},
    submittedAt: iso(daysAgo(39)),
  },
  // Phase 2: Complex — week 4 function assessment (high pain + low function triggers)
  {
    id: 'fr-ax-21-w4',
    patientId: 'p-21',
    templateId: 'qt-function-oss',
    caseId: 'case-21',
    patientJourneyId: 'pj-ax-21b',
    answers: { OSS_1: 2, OSS_2: 2, OSS_3: 2, OSS_4: 2, OSS_5: 2, PNRS_2: 8 },
    scores: { 'OSS.total': 18 },
    submittedAt: iso(daysAgo(2)),
  },

  // ── Gunnar Eriksson — Two simultaneous fractures (p-22) ──────────────────
  // Episode ep-22: Right distal radius
  {
    id: 'fr-gu-22-d1',
    patientId: 'p-22',
    templateId: 'qt-numbness-infection',
    caseId: 'case-22',
    patientJourneyId: 'pj-gu-22',
    answers: { NUMB_1: false, NUMB_2: true, INF_WOUND: false, INF_FEVER: false, PNRS_1: 6 },
    scores: {},
    submittedAt: iso(daysAgo(34)),
  },
  {
    id: 'fr-gu-22-w4',
    patientId: 'p-22',
    templateId: 'qt-function-oss',
    caseId: 'case-22',
    patientJourneyId: 'pj-gu-22',
    answers: { OSS_1: 3, OSS_2: 3, OSS_3: 3, OSS_4: 3, OSS_5: 3, PNRS_2: 4 },
    scores: { 'OSS.total': 28 },
    submittedAt: iso(daysAgo(2)),
  },
  // Episode ep-23: Left calcaneus (same patient — separate journey/case)
  {
    id: 'fr-gu-23-d1',
    patientId: 'p-22',
    templateId: 'qt-numbness-infection',
    caseId: 'case-23',
    patientJourneyId: 'pj-gu-23',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 8 },
    scores: {},
    submittedAt: iso(daysAgo(34)),
  },
  {
    id: 'fr-gu-23-w4',
    patientId: 'p-22',
    templateId: 'qt-function-oss',
    caseId: 'case-23',
    patientJourneyId: 'pj-gu-23',
    answers: { OSS_1: 1, OSS_2: 2, OSS_3: 2, OSS_4: 1, OSS_5: 1, PNRS_2: 8 },
    scores: { 'OSS.total': 15 },
    submittedAt: iso(daysAgo(1)),
  },

  // ── Birgit Magnusson — 1yr femoral + new acute radius (p-23) ─────────────
  // Episode ep-24: Femoral neck 1-year monitoring — 1yr EQ5D/OSS (LOW_FUNCTION + LOW_QOL)
  {
    id: 'fr-bi-24-1yr',
    patientId: 'p-23',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-24',
    patientJourneyId: 'pj-bi-24',
    answers: {
      EQ_MOB: '3',
      EQ_SELF: '2',
      EQ_ACT: '3',
      EQ_PAIN: '3',
      EQ_ANX: '2',
      EQ_VAS: 40,
      OSS_1: 2,
      OSS_2: 3,
      OSS_3: 2,
      OSS_4: 2,
      OSS_5: 3,
      FREE_TEXT:
        'Fortfarande svårt att gå längre sträckor. Trappor är svårt. Ny handledsskada gör det ännu svårare.',
    },
    scores: { 'OSS.total': 26, 'EQ5D.index': 0.45, EQ_VAS: 40 },
    submittedAt: iso(daysAgo(1)),
  },
  // Episode ep-25: New distal radius — day 1 acute form (HIGH_PAIN)
  {
    id: 'fr-bi-25-d1',
    patientId: 'p-23',
    templateId: 'qt-numbness-infection',
    caseId: 'case-25',
    patientJourneyId: 'pj-bi-25',
    answers: { NUMB_1: false, NUMB_2: true, INF_WOUND: false, INF_FEVER: false, PNRS_1: 7 },
    scores: {},
    submittedAt: iso(daysAgo(9)),
  },
]
