import { iso, daysAgo } from './shared'
import type { FormResponse } from '../schemas'

export const formResponses: FormResponse[] = [
  // Anders — case-1 — acute, high pain + infection
  {
    id: 'fr-1',
    patientId: 'p-1',
    templateId: 'qt-numbness-infection',
    caseId: 'case-1',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: true, INF_FEVER: true, PNRS_1: 8 },
    scores: {},
    submittedAt: iso(daysAgo(13)),
  },
  {
    id: 'fr-2',
    patientId: 'p-1',
    templateId: 'qt-wound-pain',
    caseId: 'case-1',
    answers: { WOUND_HEALED: false, WOUND_DISCHARGE: true, PNRS_2: 8, PNRS_NIGHT: 7 },
    scores: {},
    submittedAt: iso(daysAgo(4)),
  },
  // Elin — case-2 — pain increasing + low QoL
  {
    id: 'fr-3',
    patientId: 'p-2',
    templateId: 'qt-numbness-infection',
    caseId: 'case-2',
    answers: { NUMB_1: false, NUMB_2: false, INF_WOUND: false, INF_FEVER: false, PNRS_1: 7 },
    scores: {},
    submittedAt: iso(daysAgo(9)),
  },
  {
    id: 'fr-4',
    patientId: 'p-2',
    templateId: 'qt-wound-pain',
    caseId: 'case-2',
    answers: { WOUND_HEALED: true, WOUND_DISCHARGE: false, PNRS_2: 8, PNRS_NIGHT: 6 },
    scores: {},
    submittedAt: iso(daysAgo(2)),
  },
  // Karl — case-3 — subacute, good progress
  {
    id: 'fr-5',
    patientId: 'p-3',
    templateId: 'qt-function-oss',
    caseId: 'case-3',
    answers: { OSS_1: 4, OSS_2: 3, OSS_3: 4, OSS_4: 4, OSS_5: 3, PNRS_2: 3 },
    scores: { 'OSS.total': 36 },
    submittedAt: iso(daysAgo(2)),
  },
  // Britta — case-8 — subacute following up, low function
  {
    id: 'fr-8',
    patientId: 'p-8',
    templateId: 'qt-function-oss',
    caseId: 'case-8',
    answers: { OSS_1: 2, OSS_2: 2, OSS_3: 3, OSS_4: 2, OSS_5: 2, PNRS_2: 6 },
    scores: { 'OSS.total': 22 },
    submittedAt: iso(daysAgo(4)),
  },
  // Torkel — case-5 — control, low function + low QoL
  {
    id: 'fr-5b',
    patientId: 'p-5',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-5',
    answers: {
      EQ_MOB: '2',
      EQ_SELF: '1',
      EQ_ACT: '2',
      EQ_PAIN: '3',
      EQ_ANX: '2',
      EQ_VAS: 45,
      OSS_1: 2,
      OSS_2: 3,
      OSS_3: 2,
      OSS_4: 2,
      OSS_5: 3,
      FREE_TEXT: 'Jag har fortfarande ont men det är bättre än förut. Svårt att sova.',
    },
    scores: { 'OSS.total': 25, 'EQ5D.index': 0.45 },
    submittedAt: iso(daysAgo(3)),
  },
  // Maria — case-6 — closed, good result
  {
    id: 'fr-6',
    patientId: 'p-6',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-6',
    answers: {
      EQ_MOB: '1',
      EQ_SELF: '1',
      EQ_ACT: '1',
      EQ_PAIN: '1',
      EQ_ANX: '1',
      EQ_VAS: 85,
      OSS_1: 4,
      OSS_2: 4,
      OSS_3: 5,
      OSS_4: 4,
      OSS_5: 4,
      FREE_TEXT: 'Mår mycket bra. Är nöjd med behandlingen.',
    },
    scores: { 'OSS.total': 38, 'EQ5D.index': 0.9 },
    submittedAt: iso(daysAgo(7)),
  },
  // Lena — case-10 — control, triaged to physio
  {
    id: 'fr-10',
    patientId: 'p-10',
    templateId: 'qt-eq5d-oss',
    caseId: 'case-10',
    answers: {
      EQ_MOB: '2',
      EQ_SELF: '1',
      EQ_ACT: '2',
      EQ_PAIN: '2',
      EQ_ANX: '1',
      EQ_VAS: 65,
      OSS_1: 3,
      OSS_2: 3,
      OSS_3: 4,
      OSS_4: 3,
      OSS_5: 3,
      FREE_TEXT: 'Lite stel i axeln på morgnarna men förbättras under dagen.',
    },
    scores: { 'OSS.total': 32, 'EQ5D.index': 0.72 },
    submittedAt: iso(daysAgo(2)),
  },
]
