import { iso, daysAgo } from './shared'
import type { JourneyTemplate } from '../schemas'

export const journeyTemplates: JourneyTemplate[] = [
  {
    id: 'jt-standard',
    name: 'Standard Fracture',
    description: 'Standard post-operative follow-up for uncomplicated fractures',
    entries: [
      {
        id: 'jte-std-1',
        label: 'Day 1–2',
        offsetDays: 1,
        windowDays: 1,
        order: 1,
        templateId: 'qt-numbness-infection',
        dashboardCategory: 'ACUTE',
        scoreAliases: { PNRS_1: 'PNRS_baseline' },
        scoreAliasLabels: { PNRS_baseline: 'VAS (PNRS) vid dag 1–2' },
      },
      {
        id: 'jte-std-2',
        label: 'Day 10–14',
        offsetDays: 10,
        windowDays: 4,
        order: 2,
        templateId: 'qt-wound-pain',
        dashboardCategory: 'ACUTE',
        scoreAliases: { PNRS_2: 'PNRS_day14', PNRS_NIGHT: 'PNRS_NIGHT_day14' },
        scoreAliasLabels: {
          PNRS_day14: 'VAS (PNRS) vid dag 10–14',
          PNRS_NIGHT_day14: 'Nattsmärta (PNRS) vid dag 10–14',
        },
      },
      {
        id: 'jte-std-3',
        label: 'Week 4',
        offsetDays: 28,
        windowDays: 3,
        order: 3,
        templateId: 'qt-function-oss',
        dashboardCategory: 'SUBACUTE',
        scoreAliases: { PNRS_2: 'PNRS_week4', 'OSS.total': 'OSS_week4' },
        scoreAliasLabels: {
          PNRS_week4: 'VAS (PNRS) vid vecka 4',
          OSS_week4: 'OSS-poäng vid vecka 4',
        },
      },
      {
        id: 'jte-std-4',
        label: 'Week 6–8 (cast-off)',
        offsetDays: 49,
        windowDays: 7,
        order: 4,
        templateId: 'qt-function-oss',
        dashboardCategory: 'SUBACUTE',
        scoreAliases: { PNRS_2: 'PNRS_week8', 'OSS.total': 'OSS_week8' },
        scoreAliasLabels: {
          PNRS_week8: 'VAS (PNRS) vid vecka 6–8',
          OSS_week8: 'OSS-poäng vid vecka 6–8',
        },
      },
      {
        id: 'jte-std-5',
        label: '6 months',
        offsetDays: 180,
        windowDays: 14,
        order: 5,
        templateId: 'qt-eq5d-oss',
        dashboardCategory: 'CONTROL',
        scoreAliases: { 'OSS.total': 'OSS_6m', 'EQ5D.index': 'EQ5D_6m', EQ_VAS: 'EQ_VAS_6m' },
        scoreAliasLabels: {
          OSS_6m: 'OSS-poäng vid 6 månader',
          EQ5D_6m: 'EQ-5D index vid 6 månader',
          EQ_VAS_6m: 'EQ VAS vid 6 månader',
        },
      },
      {
        id: 'jte-std-6',
        label: '1 year',
        offsetDays: 365,
        windowDays: 14,
        order: 6,
        templateId: 'qt-eq5d-oss',
        dashboardCategory: 'CONTROL',
        scoreAliases: { 'OSS.total': 'OSS_1yr', 'EQ5D.index': 'EQ5D_1yr', EQ_VAS: 'EQ_VAS_1yr' },
        scoreAliasLabels: {
          OSS_1yr: 'OSS-poäng vid 1 år',
          EQ5D_1yr: 'EQ-5D index vid 1 år',
          EQ_VAS_1yr: 'EQ VAS vid 1 år',
        },
      },
    ],
    createdAt: iso(daysAgo(100)),
  },
  {
    id: 'jt-complex',
    name: 'Complex Fracture',
    description:
      'Extended follow-up for complex fractures with potential complications — adds an early wound check at Day 3–5',
    entries: [
      {
        id: 'jte-cx-1',
        label: 'Day 1–2',
        offsetDays: 1,
        windowDays: 1,
        order: 1,
        templateId: 'qt-numbness-infection',
        dashboardCategory: 'ACUTE',
        scoreAliases: { PNRS_1: 'PNRS_baseline' },
        scoreAliasLabels: { PNRS_baseline: 'VAS (PNRS) vid dag 1–2' },
      },
      {
        id: 'jte-cx-2',
        label: 'Day 3–5 (early wound check)',
        offsetDays: 4,
        windowDays: 1,
        order: 2,
        templateId: 'qt-wound-pain',
        dashboardCategory: 'ACUTE',
        scoreAliases: { PNRS_2: 'PNRS_day4' },
        scoreAliasLabels: { PNRS_day4: 'VAS (PNRS) vid dag 3–5' },
      },
      {
        id: 'jte-cx-3',
        label: 'Day 10–14',
        offsetDays: 10,
        windowDays: 4,
        order: 3,
        templateId: 'qt-wound-pain',
        dashboardCategory: 'ACUTE',
        scoreAliases: { PNRS_2: 'PNRS_day14', PNRS_NIGHT: 'PNRS_NIGHT_day14' },
        scoreAliasLabels: {
          PNRS_day14: 'VAS (PNRS) vid dag 10–14',
          PNRS_NIGHT_day14: 'Nattsmärta (PNRS) vid dag 10–14',
        },
      },
      {
        id: 'jte-cx-4',
        label: 'Week 4',
        offsetDays: 28,
        windowDays: 3,
        order: 4,
        templateId: 'qt-function-oss',
        dashboardCategory: 'SUBACUTE',
        scoreAliases: { PNRS_2: 'PNRS_week4', 'OSS.total': 'OSS_week4' },
        scoreAliasLabels: {
          PNRS_week4: 'VAS (PNRS) vid vecka 4',
          OSS_week4: 'OSS-poäng vid vecka 4',
        },
      },
      {
        id: 'jte-cx-5',
        label: 'Week 6–8 (cast-off)',
        offsetDays: 49,
        windowDays: 7,
        order: 5,
        templateId: 'qt-function-oss',
        dashboardCategory: 'SUBACUTE',
        scoreAliases: { PNRS_2: 'PNRS_week8', 'OSS.total': 'OSS_week8' },
        scoreAliasLabels: {
          PNRS_week8: 'VAS (PNRS) vid vecka 6–8',
          OSS_week8: 'OSS-poäng vid vecka 6–8',
        },
      },
      {
        id: 'jte-cx-6',
        label: '6 months',
        offsetDays: 180,
        windowDays: 14,
        order: 6,
        templateId: 'qt-eq5d-oss',
        dashboardCategory: 'CONTROL',
        scoreAliases: { 'OSS.total': 'OSS_6m', 'EQ5D.index': 'EQ5D_6m', EQ_VAS: 'EQ_VAS_6m' },
        scoreAliasLabels: {
          OSS_6m: 'OSS-poäng vid 6 månader',
          EQ5D_6m: 'EQ-5D index vid 6 månader',
          EQ_VAS_6m: 'EQ VAS vid 6 månader',
        },
      },
      {
        id: 'jte-cx-7',
        label: '1 year',
        offsetDays: 365,
        windowDays: 14,
        order: 7,
        templateId: 'qt-eq5d-oss',
        dashboardCategory: 'CONTROL',
        scoreAliases: { 'OSS.total': 'OSS_1yr', 'EQ5D.index': 'EQ5D_1yr', EQ_VAS: 'EQ_VAS_1yr' },
        scoreAliasLabels: {
          OSS_1yr: 'OSS-poäng vid 1 år',
          EQ5D_1yr: 'EQ-5D index vid 1 år',
          EQ_VAS_1yr: 'EQ VAS vid 1 år',
        },
      },
    ],
    createdAt: iso(daysAgo(100)),
  },
]
