import { iso, isoDate, daysAgo } from './shared'
import type { PatientJourney } from '../schemas'

export const patientJourneys: PatientJourney[] = [
  {
    id: 'pj-1',
    patientId: 'p-1',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(14)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(14)),
  },
  {
    id: 'pj-2',
    patientId: 'p-2',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(10)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(10)),
  },
  {
    id: 'pj-3',
    patientId: 'p-3',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(21)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(21)),
    updatedAt: iso(daysAgo(21)),
  },
  {
    id: 'pj-4',
    patientId: 'p-4',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(25)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(25)),
    updatedAt: iso(daysAgo(25)),
  },
  {
    id: 'pj-5',
    patientId: 'p-5',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(63)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(63)),
    updatedAt: iso(daysAgo(63)),
  },
  {
    id: 'pj-6',
    patientId: 'p-6',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(90)),
    status: 'COMPLETED',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(90)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'pj-7',
    patientId: 'p-7',
    journeyTemplateId: 'jt-complex',
    startDate: isoDate(daysAgo(1)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'pj-8',
    patientId: 'p-8',
    journeyTemplateId: 'jt-complex',
    startDate: isoDate(daysAgo(18)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [
      {
        id: 'jmod-8-1',
        type: 'SWITCH_TEMPLATE',
        addedByUserId: 'user-pal-1',
        addedAt: iso(daysAgo(3)),
        reason:
          'Post-op infection suspected; switching to Complex Fracture pathway for closer wound monitoring',
        previousTemplateId: 'jt-standard',
        newTemplateId: 'jt-complex',
      },
    ],
    recurringCompletions: [],
    createdAt: iso(daysAgo(18)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 'pj-9',
    patientId: 'p-9',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(70)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(70)),
    updatedAt: iso(daysAgo(70)),
  },
  {
    id: 'pj-10',
    patientId: 'p-10',
    journeyTemplateId: 'jt-standard',
    startDate: isoDate(daysAgo(100)),
    status: 'ACTIVE',
    researchModuleIds: ['rm-move-2026'],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(100)),
    updatedAt: iso(daysAgo(100)),
  },
  // ── Proximal humerus journeys ─────────────────────────────────────────
  {
    id: 'pj-11',
    patientId: 'p-11',
    journeyTemplateId: 'jt-proximal-humerus',
    startDate: isoDate(daysAgo(2)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 'pj-12',
    patientId: 'p-12',
    journeyTemplateId: 'jt-proximal-humerus',
    startDate: isoDate(daysAgo(35)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(7)),
  },
  // ── Distal radius journeys ───────────────────────────────────────────
  {
    id: 'pj-13',
    patientId: 'p-13',
    journeyTemplateId: 'jt-distal-radius',
    startDate: isoDate(daysAgo(14)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'pj-14',
    patientId: 'p-14',
    journeyTemplateId: 'jt-distal-radius',
    startDate: isoDate(daysAgo(52)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    createdAt: iso(daysAgo(52)),
    updatedAt: iso(daysAgo(3)),
  },
]
