import type { PatientJourney } from '../schemas'
import { daysAgo, iso, isoDate } from './shared'

export const patientJourneys: PatientJourney[] = [
  {
    id: 'pj-1',
    episodeId: 'ep-1',
    patientId: 'p-1',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(14)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(14)),
  },
  {
    id: 'pj-2',
    episodeId: 'ep-2',
    patientId: 'p-2',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(10)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(10)),
  },
  {
    id: 'pj-3',
    episodeId: 'ep-3',
    patientId: 'p-3',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(21)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(21)),
    updatedAt: iso(daysAgo(21)),
  },
  {
    id: 'pj-4',
    episodeId: 'ep-4',
    patientId: 'p-4',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(25)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(25)),
    updatedAt: iso(daysAgo(25)),
  },
  {
    id: 'pj-5',
    episodeId: 'ep-5',
    patientId: 'p-5',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(63)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(63)),
    updatedAt: iso(daysAgo(63)),
  },
  {
    id: 'pj-6',
    episodeId: 'ep-6',
    patientId: 'p-6',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(90)),
    status: 'COMPLETED',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(90)),
    updatedAt: iso(daysAgo(7)),
  },
  {
    id: 'pj-7',
    episodeId: 'ep-7',
    patientId: 'p-7',
    journeyTemplateId: 'jt-complex',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(1)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  // pj-8: assigned directly to Complex Fracture pathway (no template switch needed)
  {
    id: 'pj-8',
    episodeId: 'ep-8',
    patientId: 'p-8',
    journeyTemplateId: 'jt-complex',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(18)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(18)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 'pj-9',
    episodeId: 'ep-9',
    patientId: 'p-9',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(70)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(70)),
    updatedAt: iso(daysAgo(70)),
  },
  {
    id: 'pj-10',
    episodeId: 'ep-10',
    patientId: 'p-10',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(100)),
    status: 'ACTIVE',
    researchModuleIds: ['rm-move-2026'],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(100)),
    updatedAt: iso(daysAgo(100)),
  },
  // ── Proximal humerus journeys ─────────────────────────────────────────
  {
    id: 'pj-11',
    episodeId: 'ep-11',
    patientId: 'p-11',
    journeyTemplateId: 'jt-proximal-humerus',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(2)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 'pj-12',
    episodeId: 'ep-12',
    patientId: 'p-12',
    journeyTemplateId: 'jt-proximal-humerus',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(35)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(35)),
    updatedAt: iso(daysAgo(7)),
  },
  // ── Distal radius journeys ───────────────────────────────────────────
  {
    id: 'pj-13',
    episodeId: 'ep-13',
    patientId: 'p-13',
    journeyTemplateId: 'jt-distal-radius',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(14)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 'pj-14',
    episodeId: 'ep-14',
    patientId: 'p-14',
    journeyTemplateId: 'jt-distal-radius',
    phaseType: 'FOLLOWUP',
    joinedAt: '',
    startDate: isoDate(daysAgo(52)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(52)),
    updatedAt: iso(daysAgo(3)),
  },
  // ── Knee OA: 3-phase journey for Karin Karlberg ──────────────────────────
  {
    id: 'pj-knee-1',
    episodeId: 'ep-15',
    patientId: 'p-15',
    journeyTemplateId: 'jt-knee-referral',
    phaseType: 'REFERRAL',
    joinedAt: '',
    startDate: isoDate(daysAgo(120)),
    status: 'COMPLETED',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(120)),
    updatedAt: iso(daysAgo(90)),
  },
  {
    id: 'pj-knee-2',
    episodeId: 'ep-15',
    patientId: 'p-15',
    journeyTemplateId: 'jt-knee-surgery-queue',
    phaseType: 'WAITING_LIST',
    joinedAt: '',
    startDate: isoDate(daysAgo(90)),
    status: 'COMPLETED',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    transition: {
      fromJourneyId: 'pj-knee-1',
      type: 'VISIT_DECISION',
      triggeredAt: iso(daysAgo(90)),
      triggeredByUserId: 'user-pal-1',
      note: 'Besök genomfört — patient satt upp på väntelista för knäprotesoperation.',
    },
    createdAt: iso(daysAgo(90)),
    updatedAt: iso(daysAgo(14)),
  },
  {
    id: 'pj-knee-3',
    episodeId: 'ep-15',
    patientId: 'p-15',
    journeyTemplateId: 'jt-knee-postop',
    phaseType: 'POST_OP',
    joinedAt: '',
    startDate: isoDate(daysAgo(14)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    transition: {
      fromJourneyId: 'pj-knee-2',
      type: 'SURGERY_COMPLETED',
      triggeredAt: iso(daysAgo(14)),
      triggeredByUserId: 'user-pal-1',
      note: 'Operation genomförd — postoperativ rehabilitering startar.',
    },
    createdAt: iso(daysAgo(14)),
    updatedAt: iso(daysAgo(14)),
  },
  // ── Late-join demo: Lars Larsson — fracture 28 days ago, joins today ─────
  {
    id: 'pj-16',
    episodeId: 'ep-16',
    patientId: 'p-16',
    journeyTemplateId: 'jt-standard',
    phaseType: 'FOLLOWUP',
    // joinedAt = today; startDate = 28 days ago — early steps removed via late-join mods below
    joinedAt: isoDate(daysAgo(0)),
    startDate: isoDate(daysAgo(28)),
    status: 'ACTIVE',
    researchModuleIds: [],
    modifications: [
      {
        id: 'mod-pj16-1',
        type: 'REMOVE_STEP',
        addedByUserId: 'system',
        addedAt: iso(daysAgo(0)),
        reason: 'Inskrivning efter stegets fönster — patienten registrerades sent.',
        stepId: 'jte-std-1',
      },
      {
        id: 'mod-pj16-2',
        type: 'REMOVE_STEP',
        addedByUserId: 'system',
        addedAt: iso(daysAgo(0)),
        reason: 'Inskrivning efter stegets fönster — patienten registrerades sent.',
        stepId: 'jte-std-2',
      },
    ],
    recurringCompletions: [],
    pausedAt: null,
    totalPausedDays: 0,
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
]
