import { iso, daysAgo } from './shared'
import type { PolicyRule } from '../schemas'

export const policyRules: PolicyRule[] = [
  {
    id: 'rule-1',
    journeyTemplateId: 'jt-standard',
    name: 'Smärta minskar inte',
    expression: 'PNRS_1 - PNRS_2 <= 0',
    severity: 'HIGH',
    enabled: true,
    createdAt: iso(daysAgo(100)),
  },
  {
    id: 'rule-2',
    journeyTemplateId: 'jt-standard',
    name: 'Låg funktion (OSS)',
    expression: 'OSS.total < 30',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(100)),
  },
  {
    id: 'rule-3',
    journeyTemplateId: 'jt-standard',
    name: 'Låg livskvalitet (EQ-5D)',
    expression: 'EQ5D.index < 0.5',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(100)),
  },
  {
    id: 'rule-4',
    journeyTemplateId: 'jt-standard',
    name: 'Hög smärta (VAS)',
    expression: 'PNRS_2 >= 7',
    severity: 'HIGH',
    enabled: true,
    createdAt: iso(daysAgo(100)),
  },
  {
    id: 'rule-5',
    journeyTemplateId: 'jt-standard',
    name: 'Låg EQ VAS',
    expression: 'EQ_VAS < 50',
    severity: 'LOW',
    enabled: false,
    createdAt: iso(daysAgo(100)),
  },
  // ── Proximal humerus rules ────────────────────────────────────────────
  {
    id: 'rule-ph-1',
    journeyTemplateId: 'jt-proximal-humerus',
    name: 'Smärta minskar inte',
    expression: 'PNRS_1 - PNRS_2 <= 0',
    severity: 'HIGH',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-ph-2',
    journeyTemplateId: 'jt-proximal-humerus',
    name: 'Hög smärta vid vecka 4',
    expression: 'PNRS_week4 >= 7',
    severity: 'HIGH',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-ph-3',
    journeyTemplateId: 'jt-proximal-humerus',
    name: 'Låg axelfunktion vid vecka 4',
    expression: 'OSS_week4 < 25',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-ph-4',
    journeyTemplateId: 'jt-proximal-humerus',
    name: 'Kvarstående låg axelfunktion vid 6 mån',
    expression: 'OSS_6m < 30',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-ph-5',
    journeyTemplateId: 'jt-proximal-humerus',
    name: 'Låg livskvalitet vid 6 månader',
    expression: 'EQ5D_6m < 0.5',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  // ── Distal radius rules ───────────────────────────────────────────────
  {
    id: 'rule-dr-1',
    journeyTemplateId: 'jt-distal-radius',
    name: 'Smärta minskar inte',
    expression: 'PNRS_1 - PNRS_2 <= 0',
    severity: 'HIGH',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-dr-2',
    journeyTemplateId: 'jt-distal-radius',
    name: 'Hög smärta vid gipsavtagning',
    expression: 'PNRS_week4 >= 6',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-dr-3',
    journeyTemplateId: 'jt-distal-radius',
    name: 'Låg handledsfunktion efter gips',
    expression: 'OSS_week4 < 26',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-dr-4',
    journeyTemplateId: 'jt-distal-radius',
    name: 'Kvarstående låg handledsfunktion',
    expression: 'OSS_week8 < 26',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
  {
    id: 'rule-dr-5',
    journeyTemplateId: 'jt-distal-radius',
    name: 'Låg livskvalitet vid 6 månader',
    expression: 'EQ5D_6m < 0.5',
    severity: 'MEDIUM',
    enabled: true,
    createdAt: iso(daysAgo(60)),
  },
]
