/** Swedish name pools and personal number formatter for generated patients. */

export const FIRST_NAMES = [
  'Anna',
  'Erik',
  'Maria',
  'Lars',
  'Karin',
  'Stefan',
  'Ingrid',
  'Mikael',
  'Birgitta',
  'Johan',
  'Eva',
  'Anders',
  'Kristina',
  'Björn',
  'Christina',
  'Peter',
  'Margareta',
  'Karl',
  'Elisabet',
  'Nils',
  'Helena',
  'Per',
  'Gunilla',
  'Thomas',
  'Barbro',
  'Magnus',
  'Inger',
  'Mattias',
  'Monica',
  'Jonas',
  'Lena',
  'Henrik',
  'Marianne',
  'Andreas',
  'Annika',
  'Daniel',
  'Susanne',
  'Joakim',
  'Ulrika',
  'Fredrik',
  'Linda',
  'Patrik',
  'Sara',
  'Christian',
  'Emma',
  'Alexander',
  'Sofia',
  'Marcus',
  'Malin',
  'Simon',
]

export const LAST_NAMES = [
  'Johansson',
  'Andersson',
  'Karlsson',
  'Nilsson',
  'Eriksson',
  'Larsson',
  'Persson',
  'Svensson',
  'Gustafsson',
  'Pettersson',
  'Jonsson',
  'Jansson',
  'Hansson',
  'Bengtsson',
  'Jönsson',
  'Lindberg',
  'Jakobsson',
  'Magnusson',
  'Olsson',
  'Lindström',
  'Lindqvist',
  'Lindgren',
  'Berg',
  'Axelsson',
  'Bergström',
  'Lundberg',
  'Lind',
  'Lundgren',
  'Lundqvist',
  'Mattsson',
  'Berglund',
  'Fredriksson',
  'Sandberg',
  'Henriksson',
  'Forsberg',
  'Sjöberg',
  'Ali',
  'Hassan',
  'Ahmad',
  'Islamovic',
  'Nguyen',
  'Patel',
  'Anderberg',
  'Holmberg',
  'Ekström',
  'Söderberg',
  'Martinsson',
  'Nordin',
  'Holm',
  'Samuelsson',
]

export function personalNumber(birthYear: number, index: number): string {
  const mm = String((index % 12) + 1).padStart(2, '0')
  const dd = String((index % 28) + 1).padStart(2, '0')
  const seq = String(1000 + index).padStart(4, '0')
  return `${birthYear}${mm}${dd}${seq}`
}
